---
name: 📝 Documentation problem
about: Documentation is unclear or otherwise insufficient.
title: ""
labels: documentation
assignees: ""
---

<!--
  Please follow the template.  If you don't, your issue may be closed.
  Make sure to search existing issues first to avoid creating duplicates.
  Contributing guidelines: https://github.com/AlphaKretin/emcee-tournament-bot/master/.github/CONTRIBUTING.md
  Code of conduct: https://github.com/AlphaKretin/emcee-tournament-bot/master/.github/CODE_OF_CONDUCT.md


  Have a question?  This is not the right place for general support or feature requests.
  Instead, join our Discord server and send inquires that way ➡️ https://discord.gg/GrMGspZ
-->

### What was unclear or otherwise insufficient?

<!--
  If relevant, please be clear about the documentation file,
  as well as the location within the file.  Link to the documentation
  in the repository.

  If the page does not exist, please be clear why a new documentation
  section is needed.
-->


### Recommended fix

<!--
  How should we fix this documentation issue?

  Should we add examples, clarify the language, or drop the page entirely?
-->


### Additional context

<!--
  Add any other context about the documentation issue here.
-->


### Are you willing to resolve this issue by submitting a pull request?

<!--
  First-time contributors are welcome! 😊
-->

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.


<!--
  👋 Have a great day and thank you for the report!
-->
